### ISSUE TITLE
STD lib OptionParser

### ISSUE THREAD

**Issue by jkthorne** [luckyframework/lucky_task#1]
Why is luck task not using https://crystal-lang.org/api/1.0.0/OptionParser.html ?
It seems like logic could be reduced and we could lean more on the work in the std lib.

**Comment by jwoertink** [comment]
It does https://github.com/luckyframework/lucky_task/blob/master/src/lucky_task.cr#L1 

The reason it's not front and center is because OptionParser doesn't support positional arguments. A lot of our tasks like `lucky gen.model User` would end up having to be `lucky gen.model --model User`. But we do use OptionParser for defining switch flags, and standard options you might want.
